### ISSUE TITLE
Issue validating format2 workflows

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/gxformat2#61]
Mentioned in iwc chat, I'm experiencing linting format2 workflows. I'm testing with [one of the GTN workflows](https://github.com/galaxyproject/training-material/blob/main/topics/assembly/tutorials/debruijn-graph-assembly/workflows/debruijn-graph.ga) 

```
$ planemo workflow_lint ./topics/assembly/tutorials/debruijn-graph-assembly/workflows/debruijn-graph.gxwf.yml
Traceback (most recent call last):
  File "/home/hxr/arbeit/galaxy/training-material/.venv/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/commands/cmd_workflow_lint.py", line 21, in cli
    exit_code = lint_workflow_artifacts_on_paths(
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/workflow_lint.py", line 52, in lint_workflow_artifacts_on_paths
    _lint_workflow_artifacts_on_path(lint_context, path, lint_args)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/workflow_lint.py", line 74, in _lint_workflow_artifacts_on_path
    lint_context.lint("lint_structure", structure, potential_workflow_artifact_path)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/galaxy/tool_util/lint.py", line 88, in lint
    lint_func(lint_target, self)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/workflow_lint.py", line 72, in structure
    lint_func(lint_context, workflow_dict, path=path)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/gxformat2/lint.py", line 105, in lint_format2
    steps = ensure_key_if_present(lint_context, workflow_dict, 'steps', default={}, has_class=dict)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/gxformat2/lint.py", line 35, in ensure_key_if_present
    return ensure_key_has_value(lint_context, has_keys, key, value, has_class=has_class, has_value=None)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/gxformat2/lint.py", line 40, in ensure_key_has_value
    lint_context.error("expected value [{value}] with key [{key}] to be of class {clazz}", key=key, value=value, clazz=has_class)
TypeError: error() got an unexpected keyword argument 'key'

```

@mvdbeek suggested an f-string issue, I manually patched the lint file to see:

```
$ planemo workflow_lint ./topics/assembly/tutorials/debruijn-graph-assembly/workflows/debruijn-graph.gxwf.yml
Traceback (most recent call last):
  File "/home/hxr/arbeit/galaxy/training-material/.venv/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/commands/cmd_workflow_lint.py", line 21, in cli
    exit_code = lint_workflow_artifacts_on_paths(
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/workflow_lint.py", line 52, in lint_workflow_artifacts_on_paths
    _lint_workflow_artifacts_on_path(lint_context, path, lint_args)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/workflow_lint.py", line 74, in _lint_workflow_artifacts_on_path
    lint_context.lint("lint_structure", structure, potential_workflow_artifact_path)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/galaxy/tool_util/lint.py", line 88, in lint
    lint_func(lint_target, self)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/planemo/workflow_lint.py", line 72, in structure
    lint_func(lint_context, workflow_dict, path=path)
  File "/home/hxr/arbeit/galaxy/training-material/.venv/lib/python3.8/site-packages/gxformat2/lint.py", line 106, in lint_format2
    for key, step in steps.items():
AttributeError: 'list' object has no attribute 'items'
```

Package versions:

```
gxformat2==0.15.0
planemo==0.74.5
```

**Comment by hexylena** [comment]
since `steps.items()` was failing, here's what `steps` contains:

```
[OrderedDict([('tool_shed_repository', OrderedDict([('changeset_revision', '37d88f41c810'), ('name', 'velvetoptimiser'), ('owner', 'simon-gladman'), ('tool_shed', 'toolshed.g2.bx.psu.edu')])), ('tool_id', 'toolshed.g2.bx.psu.edu/repos/simon-gladman/velvetoptimiser/velvetoptimiser/2.2.6'), ('tool_version', '2.2.6'), ('position', OrderedDict([('left', 230), ('top', 10)])), ('tool_state', OrderedDict([('advanced', '{"maxCutoff": "0.8", "minCutoff": "0", "optFuncCov": "Lbp", "optFuncKmer": "n50", "velvetg_opts": "", "verbose": "false"}'), ('chromInfo', '"/opt/galaxy/tool-data/shared/ucsc/chrom/?.len"'), ('end_kmer', '"73"'), ('files', '[{"__index__": 0, "filetype": "fastq", "paired_type": {"__current_case__": 0, "input1": null, "input2": null, "paired_type_selector": "paired"}}]'), ('kmer_step', '"2"'), ('start_kmer', '"45"')])), ('in', OrderedDict([('files_0|paired_type|input1', OrderedDict([('source', 'mutant_R1')])), ('files_0|paired_type|input2', OrderedDict([('source', 'mutant_R2')]))]))]), OrderedDict([('tool_shed_repository', OrderedDict([('changeset_revision', 'b8d633fbf5f5'), ('name', 'spades'), ('owner', 'nml'), ('tool_shed', 'toolshed.g2.bx.psu.edu')])), ('tool_id', 'toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.12.0+galaxy1'), ('tool_version', '3.12.0+galaxy1'), ('position', OrderedDict([('left', 230), ('top', 130)])), ('tool_state', OrderedDict([('careful', '"true"'), ('chromInfo', '"/opt/galaxy/tool-data/shared/ucsc/chrom/?.len"'), ('contig_graph_out', '"false"'), ('cov', '{"__current_case__": 2, "state": "auto"}'), ('iontorrent', '"false"'), ('kmer_choice', '{"__current_case__": 0, "auto_kmer_choice": "false", "kmers": "33,55,91"}'), ('libraries', '[{"__index__": 0, "files": [{"__index__": 0, "file_type": {"__current_case__": 0, "fwd_reads": null, "rev_reads": null, "type": "separate"}}], "lib_type": "paired_end", "orientation": "fr"}]'), ('nanopore_reads', 'null'), ('onlyassembler', '"true"'), ('pacbio_reads', 'null'), ('sanger_reads', 'null'), ('sc', '"false"'), ('scaffold_graph_out', '"false"'), ('trusted_contigs', 'null'), ('untrusted_contigs', 'null')])), ('in', OrderedDict([('libraries_0|files_0|file_type|fwd_reads', OrderedDict([('source', 'mutant_R1')])), ('libraries_0|files_0|file_type|rev_reads', OrderedDict([('source', 'mutant_R2')]))]))]), OrderedDict([('tool_shed_repository', OrderedDict([('changeset_revision', '9c620a950d3a'), ('name', 'fasta_stats'), ('owner', 'iuc'), ('tool_shed', 'toolshed.g2.bx.psu.edu')])), ('tool_id', 'toolshed.g2.bx.psu.edu/repos/iuc/fasta_stats/fasta-stats/1.0.1'), ('tool_version', '1.0.1'), ('position', OrderedDict([('left', 450), ('top', 10)])), ('tool_state', OrderedDict([('chromInfo', '"/opt/galaxy/tool-data/shared/ucsc/chrom/?.len"'), ('dataset', 'null')])), ('in', OrderedDict([('dataset', OrderedDict([('source', '2/contigs')]))]))]), OrderedDict([('tool_shed_repository', OrderedDict([('changeset_revision', '9c620a950d3a'), ('name', 'fasta_stats'), ('owner', 'iuc'), ('tool_shed', 'toolshed.g2.bx.psu.edu')])), ('tool_id', 'toolshed.g2.bx.psu.edu/repos/iuc/fasta_stats/fasta-stats/1.0.1'), ('tool_version', '1.0.1'), ('position', OrderedDict([('left', 450), ('top', 130)])), ('tool_state', OrderedDict([('chromInfo', '"/opt/galaxy/tool-data/shared/ucsc/chrom/?.len"'), ('dataset', 'null')])), ('in', OrderedDict([('dataset', OrderedDict([('source', '3/out_contigs')]))]))])]
```

**Comment by hexylena** [comment]
I labelled every step, and now I'm getting a different fun error:

```
$ planemo workflow_lint Galaxy-Workflow-Genome_Assembly_of_MRSA_using_Illumina_MiSeq_Data_\(imported_from_uploaded_file\).gxwf.yml
Applying linter structure... FAIL
.. ERROR: Validation failed [Errno 2] No such file or directory: ''
Applying linter tests... WARNING
.. WARNING: Workflow missing test cases.
```

I can't attach it for some reason so here's the WF

```
class: GalaxyWorkflow
doc: Genome Assembly of MRSA using Illumina MiSeq Data
label: Genome Assembly of MRSA using Illumina MiSeq Data (imported from uploaded file)
tags:
- assembly
uuid: d48d3046-84ff-443f-88a9-3855e8483a91
inputs:
  DRR187559_1:
    doc: Forward read set
    format:
    - fastqsanger
    optional: false
    position:
      bottom: 901.1999969482422
      height: 82.19999694824219
      left: -944.5
      right: -744.5
      top: 819
      width: 200
      x: -944.5
      y: 819
    type: data
  DRR187559_2:
    doc: Reverse Read set
    format:
    - fastqsanger
    optional: false
    position:
      bottom: 1009.1999969482422
      height: 82.19999694824219
      left: -952.5
      right: -752.5
      top: 927
      width: 200
      x: -952.5
      y: 927
    type: data
outputs:
  trimmed_reads_r1:
    outputSource: trimmomatic/fastq_out_r1_paired
  trimmed_reads_r2:
    outputSource: trimmomatic/fastq_out_r2_paired
  final_contig:
    outputSource: shovill/contigs
  detailed_stats.tsv:
    outputSource: staramr/detailed_summary
  quast_html_report:
    outputSource: quast/report_html
  bandage:
    outputSource: bandage/outfile
  multiqc:
    outputSource: multiqc/html_report
  jbrowse:
    outputSource: jbrowse
steps:
  fastqc_r1:
    tool_shed_repository:
      changeset_revision: e7b2202befea
      name: fastqc
      owner: devteam
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72+galaxy1
    tool_version: 0.72+galaxy1
    position:
      bottom: 1682.3999938964844
      height: 296.3999938964844
      left: -612.5
      right: -412.5
      top: 1386
      width: 200
      x: -612.5
      y: 1386
    tool_state:
      __input_ext: fastqsanger
      adapters: null
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      contaminants: null
      input_file:
        __class__: ConnectedValue
      kmers: '7'
      limits: null
      min_length: null
      nogroup: 'false'
    in:
      input_file:
        source: DRR187559_1
    out:
      html_file:
        hide: true
      text_file:
        hide: true
  trimmomatic:
    tool_shed_repository:
      changeset_revision: d94aff5ee623
      name: trimmomatic
      owner: pjbriggs
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/pjbriggs/trimmomatic/trimmomatic/0.38.1
    tool_version: 0.38.1
    position:
      bottom: 1088.3999938964844
      height: 296.3999938964844
      left: -638.5
      right: -438.5
      top: 792
      width: 200
      x: -638.5
      y: 792
    tool_state:
      illuminaclip:
        __current_case__: 1
        do_illuminaclip: 'false'
      operations:
      - __index__: 0
        operation:
          __current_case__: 2
          leading: '20'
          name: LEADING
      - __index__: 1
        operation:
          __current_case__: 3
          name: TRAILING
          trailing: '20'
      - __index__: 2
        operation:
          __current_case__: 0
          name: SLIDINGWINDOW
          required_quality: '20'
          window_size: '4'
      - __index__: 3
        operation:
          __current_case__: 1
          minlen: '30'
          name: MINLEN
      output_err: 'false'
      output_logs: 'false'
      readtype:
        __current_case__: 1
        fastq_r1_in:
          __class__: RuntimeValue
        fastq_r2_in:
          __class__: RuntimeValue
        single_or_paired: pair_of_files
    in:
      readtype|fastq_r1_in:
        source: DRR187559_1
      readtype|fastq_r2_in:
        source: DRR187559_2
    out:
      fastq_out_r1_unpaired:
        hide: true
      fastq_out_r2_unpaired:
        hide: true
  fastqc_r2:
    tool_shed_repository:
      changeset_revision: e7b2202befea
      name: fastqc
      owner: devteam
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72+galaxy1
    tool_version: 0.72+galaxy1
    position:
      bottom: 2016.3999938964844
      height: 296.3999938964844
      left: -612.5
      right: -412.5
      top: 1720
      width: 200
      x: -612.5
      y: 1720
    tool_state:
      __input_ext: fastqsanger
      adapters: null
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      contaminants: null
      input_file:
        __class__: ConnectedValue
      kmers: '7'
      limits: null
      min_length: null
      nogroup: 'false'
    in:
      input_file:
        source: DRR187559_2
    out:
      html_file:
        hide: true
      text_file:
        hide: true
  shovill:
    tool_shed_repository:
      changeset_revision: 83ead2be47b2
      name: shovill
      owner: iuc
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/iuc/shovill/shovill/1.1.0+galaxy0
    tool_version: 1.1.0+galaxy0
    position:
      bottom: 1144.6000061035156
      height: 245.60000610351562
      left: -331.5
      right: -131.5
      top: 899
      width: 200
      x: -331.5
      y: 899
    tool_state:
      adv:
        depth: '100'
        gsize: '2914567'
        kmers: ''
        mincov: '2'
        minlen: '500'
        namefmt: contig%05d
        nocorr: 'true'
        opts: ''
      assembler: spades
      library:
        R1:
          __class__: RuntimeValue
        R2:
          __class__: RuntimeValue
        __current_case__: 0
        lib_type: paired
      log: 'true'
      trim: 'false'
    in:
      library|R1:
        source: trimmomatic/fastq_out_r1_paired
      library|R2:
        source: trimmomatic/fastq_out_r2_paired
    out:
      contigs_graph:
        hide: true
      shovill_std_log:
        hide: true
  fastqc_trimmed_r1:
    tool_shed_repository:
      changeset_revision: e7b2202befea
      name: fastqc
      owner: devteam
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72+galaxy1
    tool_version: 0.72+galaxy1
    position:
      bottom: 1533.7999877929688
      height: 316.79998779296875
      left: -325.5
      right: -125.5
      top: 1217
      width: 200
      x: -325.5
      y: 1217
    tool_state:
      __input_ext: fastqsanger
      adapters: null
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      contaminants: null
      input_file:
        __class__: ConnectedValue
      kmers: '7'
      limits: null
      min_length: null
      nogroup: 'false'
    in:
      input_file:
        source: trimmomatic/fastq_out_r2_paired
    out:
      html_file:
        hide: true
      text_file:
        hide: true
  fastqc_trimmed_r2:
    tool_shed_repository:
      changeset_revision: e7b2202befea
      name: fastqc
      owner: devteam
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72+galaxy1
    tool_version: 0.72+galaxy1
    position:
      bottom: 1885.7999877929688
      height: 316.79998779296875
      left: -326.5
      right: -126.5
      top: 1569
      width: 200
      x: -326.5
      y: 1569
    tool_state:
      __input_ext: fastqsanger
      adapters: null
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      contaminants: null
      input_file:
        __class__: ConnectedValue
      kmers: '7'
      limits: null
      min_length: null
      nogroup: 'false'
    in:
      input_file:
        source: trimmomatic/fastq_out_r1_paired
    out:
      html_file:
        hide: true
      text_file:
        hide: true
  bowtie2:
    tool_shed_repository:
      changeset_revision: 749c918495f7
      name: bowtie2
      owner: devteam
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/devteam/bowtie2/bowtie2/2.3.4.3+galaxy0
    tool_version: 2.3.4.3+galaxy0
    position:
      bottom: 578.7999877929688
      height: 306.79998779296875
      left: -26.5
      right: 173.5
      top: 272
      width: 200
      x: -26.5
      y: 272
    tool_state:
      __input_ext: input
      analysis_type:
        __current_case__: 0
        analysis_type_selector: simple
        presets: no_presets
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      library:
        __current_case__: 1
        aligned_file: 'false'
        input_1:
          __class__: ConnectedValue
        input_2:
          __class__: ConnectedValue
        paired_options:
          __current_case__: 1
          paired_options_selector: 'no'
        type: paired
        unaligned_file: 'false'
      reference_genome:
        __current_case__: 1
        own_file:
          __class__: ConnectedValue
        source: history
      rg:
        __current_case__: 3
        rg_selector: do_not_set
      sam_options:
        __current_case__: 1
        sam_options_selector: 'no'
      save_mapping_stats: 'true'
    in:
      library|input_1:
        source: trimmomatic/fastq_out_r1_paired
      library|input_2:
        source: trimmomatic/fastq_out_r2_paired
      reference_genome|own_file:
        source: shovill/contigs
    out:
      mapping_stats:
        hide: true
      output:
        hide: true
  staramr:
    tool_shed_repository:
      changeset_revision: 2fd4d4c9c5c2
      name: staramr
      owner: nml
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/nml/staramr/staramr_search/0.7.1+galaxy2
    tool_version: 0.7.1+galaxy2
    position:
      bottom: 1188.2000122070312
      height: 571.2000122070312
      left: -29.5
      right: 170.5
      top: 617
      width: 200
      x: -29.5
      y: 617
    tool_state:
      advanced:
        exclude_genes:
          __current_case__: 0
          exclude_genes_condition: default
        exclude_negatives: 'false'
        exclude_resistance_phenotypes: 'false'
        genome_size_lower_bound: '4000000'
        genome_size_upper_bound: '6000000'
        minimum_N50_value: '10000'
        minimum_contig_length: '300'
        mlst_scheme: auto
        pid_threshold: '98.0'
        plasmidfinder_type: include_all
        plength_plasmidfinder: '60.0'
        plength_pointfinder: '95.0'
        plength_resfinder: '60.0'
        report_all_blast: 'false'
        unacceptable_number_contigs: '1000'
      genomes:
        __class__: RuntimeValue
      use_pointfinder: disabled
    in:
      genomes:
        source: shovill/contigs
    out:
      blast_hits:
        hide: true
      excel:
        hide: true
      mlst:
        hide: true
      plasmidfinder:
        hide: true
      resfinder:
        hide: true
      settings:
        hide: true
      summary:
        hide: true
  quast:
    tool_shed_repository:
      changeset_revision: ebb0dcdb621a
      name: quast
      owner: iuc
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/iuc/quast/quast/5.0.2+galaxy1
    tool_version: 5.0.2+galaxy1
    position:
      bottom: 1533
      height: 266
      left: -26.5
      right: 173.5
      top: 1267
      width: 200
      x: -26.5
      y: 1267
    tool_state:
      al:
        ambiguity_score: '0.99'
        ambiguity_usage: one
        fragmented: 'false'
        fragmented_max_indent: '50'
        min_alignment: '65'
        min_identity: '95.0'
        upper_bound_assembly: 'false'
        upper_bound_min_con: '2'
        use_all_alignments: 'false'
      assembly:
        __current_case__: 0
        orga_type: ''
        ref:
          __current_case__: 1
          est_ref_size: null
          use_ref: 'false'
        type: genome
      circos: 'false'
      contig_thresholds: 0,1000
      extensive_mis_size: '1000'
      genes:
        conserved_genes_finding: 'false'
        gene_finding:
          __current_case__: 0
          tool: none
        rna_finding: 'false'
      in:
        __current_case__: 1
        custom: 'false'
        inputs:
          __class__: ConnectedValue
      k_mer:
        __current_case__: 1
        k_mer_stats: ''
      large: 'false'
      min_contig: '500'
      scaffold_gap_max_size: '1000'
      skip_unaligned_mis_contigs: 'true'
      split_scaffolds: 'false'
      strict_NA: 'false'
      unaligned_part_size: '500'
    in:
      in|inputs:
        source: shovill/contigs
    out:
      log:
        hide: true
      quast_tabular:
        hide: true
      report_pdf:
        hide: true
  prokka:
    tool_shed_repository:
      changeset_revision: 111884f0d912
      name: prokka
      owner: crs4
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.5+galaxy0
    tool_version: 1.14.5+galaxy0
    position:
      bottom: 1574.6000061035156
      height: 235.60000610351562
      left: 529.5
      right: 729.5
      top: 1339
      width: 200
      x: 529.5
      y: 1339
    tool_state:
      __input_ext: fasta
      centre: ''
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      compliant:
        __current_case__: 0
        addgenes: 'false'
        compliant_select: 'no'
        mincontig: '200'
      evalue: 1e-06
      fast: 'false'
      genus: staphylococcus
      gffver: '3'
      increment: '1'
      input:
        __class__: ConnectedValue
      kingdom:
        __current_case__: 1
        gcode: '11'
        kingdom_select: Bacteria
      locustag: ''
      metagenome: 'false'
      norrna: 'false'
      notrna: 'false'
      outputs:
      - gff
      plasmid: ''
      proteins: null
      rfam: 'false'
      species: aureus
      strain: ''
      usegenus: 'false'
    in:
      input:
        source: shovill/contigs
    out:
      out_gff:
        hide: true
      out_log:
        hide: true
  bandage:
    tool_shed_repository:
      changeset_revision: b2860df42e16
      name: bandage
      owner: iuc
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/iuc/bandage/bandage_image/0.8.1+galaxy2
    tool_version: 0.8.1+galaxy2
    position:
      bottom: 1727.6000061035156
      height: 113.60000610351562
      left: -26.5
      right: 173.5
      top: 1614
      width: 200
      x: -26.5
      y: 1614
    tool_state:
      height: '1000'
      input_file:
        __class__: RuntimeValue
      lengths: 'false'
      names: 'false'
      output_format: jpg
      width: null
    in:
      input_file:
        source: shovill/contigs_graph
  multiqc:
    tool_shed_repository:
      changeset_revision: f7985e0479b9
      name: multiqc
      owner: iuc
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.9
    tool_version: '1.9'
    position:
      bottom: 1991.3999938964844
      height: 164.39999389648438
      left: -26.5
      right: 173.5
      top: 1827
      width: 200
      x: -26.5
      y: 1827
    tool_state:
      comment: ''
      export: 'false'
      flat: 'false'
      results:
      - __index__: 0
        software_cond:
          __current_case__: 8
          output:
          - __index__: 0
            input:
              __class__: RuntimeValue
            type: data
          software: fastqc
      saveLog: 'false'
      title: ''
    in:
      results_0|software_cond|output_0|input:
        source: fastqc_r1/text_file
    out:
      stats:
        hide: true
  select:
    tool_id: Grep1
    tool_version: 1.0.3
    position:
      bottom: 970.1999969482422
      height: 93.19999694824219
      left: 251.5
      right: 451.5
      top: 877
      width: 200
      x: 251.5
      y: 877
    tool_state:
      __input_ext: tabular
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      input:
        __class__: ConnectedValue
      invert: ''
      keep_header: 'false'
      pattern: '[0-9]+\.[0-9]+\t'
    in:
      input:
        source: staramr/detailed_summary
    out:
      out_file1:
        hide: true
  table2gff3:
    tool_shed_repository:
      changeset_revision: 4a7f4b0cc0a3
      name: tbl2gff3
      owner: iuc
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/iuc/tbl2gff3/tbl2gff3/1.2
    tool_version: '1.2'
    position:
      bottom: 960.1999969482422
      height: 93.19999694824219
      left: 529.5
      right: 729.5
      top: 867
      width: 200
      x: 529.5
      y: 867
    tool_state:
      __input_ext: tabular
      attributes:
      - __index__: 0
        key: Name
        val: '2'
      - __index__: 1
        key: phenotype
        val: '4'
      begin: '9'
      chromInfo: /opt/galaxy/tool-data/shared/ucsc/chrom/?.len
      end: '10'
      rid: '8'
      score: '5'
      source: '3'
      strand:
        __current_case__: 1
        strand_select: infer
      table:
        __class__: ConnectedValue
      type: sequence_feature
    in:
      table:
        source: select/out_file1
    out:
      output:
        hide: true
  jbrowse:
    tool_shed_repository:
      changeset_revision: 6cd09d7b5f37
      name: jbrowse
      owner: iuc
      tool_shed: toolshed.g2.bx.psu.edu
    tool_id: toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/jbrowse/1.16.10+galaxy0
    tool_version: 1.16.10+galaxy0
    position:
      bottom: 521.7999877929688
      height: 306.79998779296875
      left: 822.5
      right: 1022.5
      top: 215
      width: 200
      x: 822.5
      y: 215
    tool_state:
      action:
        __current_case__: 0
        action_select: create
      gencode: '1'
      jbgen:
        aboutDescription: ''
        defaultLocation: ''
        hideGenomeOptions: 'false'
        shareLink: 'true'
        show_menu: 'true'
        show_nav: 'true'
        show_overview: 'true'
        show_tracklist: 'true'
        trackPadding: '20'
      plugins:
        BlastView: 'true'
        ComboTrackSelector: 'false'
        GCContent: 'false'
      reference_genome:
        __current_case__: 1
        genome:
          __class__: RuntimeValue
        genome_type_select: history
      standalone: minimal
      track_groups:
      - __index__: 0
        category: Prokka
        data_tracks:
        - __index__: 0
          data_format:
            __current_case__: 2
            annotation:
              __class__: RuntimeValue
            data_format_select: gene_calls
            index: 'false'
            jb_custom_config:
              option: []
            jbcolor_scale:
              color_score:
                __current_case__: 0
                color:
                  __current_case__: 0
                  color_select: automatic
                color_score_select: none
            jbmenu:
              track_menu: []
            jbstyle:
              max_height: '600'
              style_classname: feature
              style_description: note,description
              style_height: 10px
              style_label: product,name,id
            match_part:
              __current_case__: 1
              match_part_select: 'false'
            override_apollo_drag: 'False'
            override_apollo_plugins: 'False'
            track_config:
              __current_case__: 3
              html_options:
                topLevelFeatures: ''
              track_class: NeatHTMLFeatures/View/Track/NeatFeatures
            track_visibility: default_on
      - __index__: 1
        category: Sequencing
        data_tracks:
        - __index__: 0
          data_format:
            __current_case__: 3
            annotation:
              __class__: RuntimeValue
            auto_snp: 'false'
            chunkSizeLimit: '5000000'
            data_format_select: pileup
            jb_custom_config:
              option: []
            override_apollo_drag: 'False'
            override_apollo_plugins: 'False'
            track_visibility: default_on
      - __index__: 2
        category: AMR
        data_tracks:
        - __index__: 0
          data_format:
            __current_case__: 2
            annotation:
              __class__: RuntimeValue
            data_format_select: gene_calls
            index: 'false'
            jb_custom_config:
              option: []
            jbcolor_scale:
              color_score:
                __current_case__: 1
                color_scheme:
                  __current_case__: 0
                  color:
                    __current_case__: 0
                    color_select: automatic
                  score_scheme: opacity
                color_score_select: score
                score_scales:
                  __current_case__: 0
                  scale_select: automatic
                score_scaling: linear
            jbmenu:
              track_menu: []
            jbstyle:
              max_height: '600'
              style_classname: feature
              style_description: note,description
              style_height: 10px
              style_label: product,name,id
            match_part:
              __current_case__: 1
              match_part_select: 'false'
            override_apollo_drag: 'False'
            override_apollo_plugins: 'False'
            track_config:
              __current_case__: 4
              canvas_options:
                impliedUTRs: 'false'
                subParts: ''
                transcriptType: ''
              track_class: NeatCanvasFeatures/View/Track/NeatFeatures
            track_visibility: default_on
      uglyTestingHack: ''
    in:
      reference_genome|genome:
        source: shovill/contigs
      track_groups_0|data_tracks_0|data_format|annotation:
        source: prokka/out_gff
      track_groups_1|data_tracks_0|data_format|annotation:
        source: bowtie2
      track_groups_2|data_tracks_0|data_format|annotation:
        source: table2gff3
```
