### ISSUE TITLE
collection type is lost on conversion to gxformat2

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/gxformat2#67]
```json
        "0": {
            "annotation": "Paired End FASTQ Collection",
            "content_id": null,
            "errors": null,
            "id": 0,
            "input_connections": {},
            "inputs": [
                {
                    "description": "Paired End FASTQ Collection",
                    "name": "pe-fastq"
                }
            ],
            "label": "pe-fastq",
            "name": "Input dataset collection",
            "outputs": [],
            "position": {
                "bottom": 413.01134872436523,
                "height": 60.96590805053711,
                "left": 685.9375,
                "right": 885.9375,
                "top": 352.0454406738281,
                "width": 200,
                "x": 685.9375,
                "y": 352.0454406738281
            },
            "tool_id": null,
            "tool_state": "{\"optional\": false, \"format\": [\"fastq\", \"fastq.gz\"], \"collection_type\": \"paired\"}",
            "tool_version": null,
            "type": "data_collection_input",
            "uuid": "f37e640f-e253-4d8b-a27c-497f4227dc69",
            "workflow_outputs": []
        },
```
becomes
```yaml
  pe-fastq:
    doc: Paired End FASTQ Collection
    format:
    - fastq
    - fastq.gz
    optional: false
    position:
      left: 685.9375
      top: 352.0454406738281
    type: collection
```
